# main service
dmamaievaa/java-explore-with-me pull request #2
Opened 2024-11-23 09:43 UTC by dmamaievaa

2024-11-24 14:41 UTC, afomkina requested changes

2024-11-24 14:41 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/category/controller/CategoryPublicController.java
> +            @RequestParam(defaultValue = "0") @Min(0) int from,
0 и 10 повторяются по всему проекту, лучше тоже вынести их в константы и переиспользовать

2024-11-24 14:41 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +       if (size <= 0) {
Можно избавить от данной проверки, если добавить валидацию для поля size в контроллере

2024-11-24 14:41 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/complitation/model/Compilation.java
> +    name = "compilations_to_event",
Нужно поправить по code-style (Ctrl+Alt+L)

2024-11-24 14:41 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/complitation/repository/CompilationRepository.java
> +
Лишний отступ

2024-11-24 14:41 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/complitation/repository/CompilationRepository.java
> +    Page<Compilation> findAllByPinned(boolean pinned, Pageable pageable);
Лучше возвращать `List`, так как по сути объект `Page`  нам не нужен. Мы просто пересобираем результат в список в сервисе

2024-11-24 14:41 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/category/mapper/CategoryMapper.java
> +    public Category toNewCategoryDto(NewCategoryDto newCategoryDto) {
Метод нигде не используется

2024-11-24 14:41 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/complitation/service/CompilationServiceImpl.java
> +        StringBuilder updatedFieldsLog = new StringBuilder();
Зачем нужен этот билдер? Ниже они нигде не используется

2024-11-24 14:41 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/events/dto/SearchEventParamsAdmin.java
> +    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
Лучше вынести повторяющийся паттерн в глобальные константы

2024-11-24 14:41 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/events/repository/EventRepository.java
> +    Page<Event> findAllByInitiator(User initiator, Pageable pageable);
Лучше сразу возвращать список

2024-11-24 14:41 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/events/service/EventStatServiceImpl.java
> +public class EventStatServiceImpl implements EventStatService {
Молодец, что вынесла работу с клиентом в отдельный сервис

2024-11-24 14:41 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/exception/ApiError.java
> +public class ApiError {
Не хватает модификаторов доступа у полей

2024-11-24 14:41 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/exception/InvalidParamException.java
> +public class InvalidParamException extends RuntimeException {
Этот эксепшен нигде не используется

2024-11-24 14:41 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/request/repository/RequestRepository.java
> +    Collection<ParticipationRequest> findByEvent(Event event);
Лучше возвращать более узкий интерфейс для коллекции, список или сет

2024-11-24 14:41 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/user/repository/UserRepository.java
> +    Page<User> findByIdIn(List<Integer> ids, Pageable pageable);
Лучше сразу возвращать список

2024-11-24 15:00 UTC, dmamaievaa commented on main-service/src/main/java/ru/practicum/ewm/complitation/service/CompilationServiceImpl.java
> +        StringBuilder updatedFieldsLog = new StringBuilder();
для тестов добавляла логирование вообще всего, забыла удалить

2024-11-25 18:30 UTC, afomkina approved these changes
Получилась отличная основная часть диплома, молодец 👍

2024-11-25 18:47 UTC, merged