# Реализация доп фичи
dmamaievaa/java-explore-with-me pull request #5
Opened 2024-11-28 13:39 UTC by dmamaievaa

2024-11-28 14:25 UTC, afomkina requested changes

2024-11-28 14:25 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/events/repository/EventRepository.java
> +    Page<Event> findAllByState(State state, Pageable pageable);
Лучше сразу возвращать `List`

2024-11-28 14:25 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/likes/controller/LikesAdminController.java
> +                             @RequestParam(defaultValue = DEFAULT_FROM + "") Integer from,
Может быть лучше сделать `DEFAULT_FROM` строкой, чем постоянно кастовать int подобным способом?

2024-11-28 14:25 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/likes/repository/LikesRepository.java
> +    Page<Like> findAllByEventIdAndUserId(Integer eventId, Integer userId, Pageable pageable);
Нужно возвращать `List`, вместо `Page`

2024-11-28 14:45 UTC, dmamaievaa commented on main-service/src/main/java/ru/practicum/ewm/likes/controller/LikesAdminController.java
> +                             @RequestParam(defaultValue = DEFAULT_FROM + "") Integer from,
переделала в этом классе, думала просто переиспользовать уже существующие константы

2024-11-29 11:51 UTC, afomkina approved these changes
Получилась отличная фича! Она полностью соответствует тз, выглядит чисто и структурированно, молодец 👍

2024-11-29 12:40 UTC, merged